apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apache-ignite-cluster
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: ignite
    spec:
      containers:
      - name: apache-ignite-node
        image: vishnunair/docker-ignite:latest
        env:
        - name: OPTION_LIBS
          value: ignite-kubernetes
        - name: CONFIG_URI
          value: file:///data/example-kube.xml
        ports:
        - containerPort: 11211 # REST port number.
        - containerPort: 47100 # communication SPI port number.
        - containerPort: 47500 # discovery SPI port number.
        - containerPort: 49112 # JMX port number.
